version: "3.1"

services:
  db:
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: itsecwb
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
