name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install Git
        run: sudo apt install git
      - name: Configure git user
        run: |
          git config --global user.name 'Github'
          git config --global user.email 'github@users.noreply.github.com'
      - name: Determine version bump
        id: version_bump
        run: | 
          if [[ "${{ github.event.head_commit.message }}"  =~ ^"BREAKING CHANGE" ]]; then
            echo "bump=major" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.head_commit.message }}"  =~ ^"feat" ]]; then
            echo "bump=minor" >> $GITHUB_OUTPUT
          else
            echo "bump=patch" >> $GITHUB_OUTPUT
          fi
      - name: Increment Version
        working-directory: ./packages/web
        run: yarn version --${{ steps.version_bump.outputs.bump }} -m "[ci skip](web) %s"